variables:
  MAVEN_OPTS: -Dmaven.repo.local=/root/.m2

stages:
  - upload

upload-repo:
  image: maven:3-jdk-8-slim
  stage: upload
  script: "mvn deploy -DskipTests -B -U -Dmaven.wagon.http.ssl.insecure=true"
  only:
    - master
    - develop